# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import promotions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation_Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, max_length=400, null=True)),
                ('nb_heures', models.FloatField()),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectation_enseignant', to='formations.Enseignant')),
            ],
            options={
                'verbose_name_plural': '4. Affectation Enseignant',
            },
        ),
        migrations.CreateModel(
            name='Affectation_Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '4. Affectation Etudiant',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('code_nip', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=promotions.models.get_image_path)),
                ('etudid', models.CharField(blank=True, max_length=10, null=True)),
                ('etat', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(max_length=30)),
                ('nom_usuel', models.CharField(blank=True, max_length=30, null=True)),
                ('prenom', models.CharField(max_length=30)),
                ('inscriptionstr', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('email_perso', models.EmailField(blank=True, max_length=70, null=True)),
                ('domicile', models.CharField(blank=True, max_length=100, null=True)),
                ('villedomicile', models.CharField(blank=True, max_length=100, null=True)),
                ('codepostaldomicile', models.IntegerField(blank=True, null=True)),
                ('paysdomicile', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephonemobile', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.CharField(blank=True, max_length=12, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=12, null=True)),
                ('bac', models.CharField(blank=True, max_length=12, null=True)),
                ('specialite', models.CharField(blank=True, max_length=12, null=True)),
                ('annee_bac', models.IntegerField(blank=True, null=True)),
                ('nomlycee', models.CharField(blank=True, max_length=100, null=True)),
                ('villelycee', models.CharField(blank=True, max_length=100, null=True)),
                ('codepostallycee', models.IntegerField(blank=True, null=True)),
                ('codelycee', models.CharField(blank=True, max_length=20, null=True)),
                ('type_admission', models.CharField(blank=True, max_length=20, null=True)),
                ('boursier_prec', models.CharField(blank=True, max_length=20, null=True)),
                ('debouche', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('C', 'Cours'), ('TD', 'TD'), ('TP', 'TP'), ('A', 'Autres')], default='C', max_length=5)),
            ],
            options={
                'verbose_name_plural': '3. Groupes',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=2017)),
                ('rentree', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('etudiants', models.ManyToManyField(through='promotions.Affectation_Etudiant', to='promotions.Etudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Formation')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant')),
            ],
            options={
                'ordering': ['-rentree'],
                'verbose_name_plural': '1. Promotions',
            },
        ),
        migrations.AddField(
            model_name='groupe',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Promotion'),
        ),
        migrations.AddField(
            model_name='affectation_etudiant',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid1', to='promotions.Etudiant'),
        ),
        migrations.AddField(
            model_name='affectation_etudiant',
            name='groupe_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_C', to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='affectation_etudiant',
            name='groupe_TD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_TD', to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='affectation_etudiant',
            name='groupe_TP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_TP', to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='affectation_etudiant',
            name='groupe_autre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_autre', to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='affectation_etudiant',
            name='groupe_autre2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_autre2', to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='affectation_etudiant',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid2', to='promotions.Promotion'),
        ),
        migrations.AddField(
            model_name='affectation_enseignant',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectation_groupe', to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='affectation_enseignant',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectation_module', to='formations.Module'),
        ),
    ]
