# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_auto_20170724_2149'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation_etudiant',
            name='parcours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Parcours'),
        ),
        migrations.AlterField(
            model_name='affectation_etudiant',
            name='groupe_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff_groupe_C', to='promotions.Groupe'),
        ),
        migrations.AlterField(
            model_name='affectation_etudiant',
            name='groupe_TD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff_groupe_TD', to='promotions.Groupe'),
        ),
        migrations.AlterField(
            model_name='affectation_etudiant',
            name='groupe_TP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff_groupe_TP', to='promotions.Groupe'),
        ),
        migrations.AlterField(
            model_name='affectation_etudiant',
            name='groupe_autre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff_groupe_autre', to='promotions.Groupe'),
        ),
        migrations.AlterField(
            model_name='affectation_etudiant',
            name='groupe_autre2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff_groupe_autre2', to='promotions.Groupe'),
        ),
    ]
