# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_notes_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RemoveField(
            model_name='affectation_etudiant',
            name='bulletin',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='affectation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promotions.Affectation_Etudiant'),
            preserve_default=False,
        ),
    ]
