# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20170725_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='affectation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='promotions.Affectation_Etudiant'),
        ),
    ]
