# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_auto_20170725_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_bac2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='bac2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='etablissement_bac2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
