# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_auto_20170725_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
