# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_etudiant_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='code_nip',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
