# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_bulletin_moyenne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='moyenne',
            field=models.FloatField(default=0),
        ),
    ]
