# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0011_auto_20170725_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation_enseignant',
            options={'ordering': ['module'], 'verbose_name_plural': '4. Affectation Enseignant'},
        ),
    ]
