# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0013_groupe_parcours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='parcours',
        ),
    ]
