# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0015_auto_20170819_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation_etudiant',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='promotions.Etudiant'),
        ),
        migrations.AlterField(
            model_name='affectation_etudiant',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='promotions.Promotion'),
        ),
    ]
