# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0016_auto_20170820_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.CharField(blank=True, default='2017-09-01', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rentree',
            field=models.DateField(blank=True, default='2017-09-01', null=True),
        ),
    ]
