# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0019_auto_20170902_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation_etudiant',
            name='groupe_C',
        ),
        migrations.RemoveField(
            model_name='affectation_etudiant',
            name='groupe_TD',
        ),
        migrations.RemoveField(
            model_name='affectation_etudiant',
            name='groupe_TP',
        ),
        migrations.RemoveField(
            model_name='affectation_etudiant',
            name='groupe_autre',
        ),
        migrations.RemoveField(
            model_name='affectation_etudiant',
            name='groupe_autre2',
        ),
    ]
