# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import promotions.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0020_auto_20170902_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nip', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=promotions.models.get_image_path)),
                ('etudid', models.CharField(blank=True, max_length=10, null=True)),
                ('etat', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(max_length=30)),
                ('nom_usuel', models.CharField(blank=True, max_length=30, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], default='M', max_length=10, null=True)),
                ('prenom', models.CharField(max_length=30)),
                ('inscriptionstr', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('email_perso', models.EmailField(blank=True, max_length=70, null=True)),
                ('domicile', models.CharField(blank=True, max_length=100, null=True)),
                ('villedomicile', models.CharField(blank=True, max_length=100, null=True)),
                ('codepostaldomicile', models.IntegerField(blank=True, null=True)),
                ('paysdomicile', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephonemobile', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.CharField(blank=True, default='2017-09-01', max_length=12, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=12, null=True)),
                ('bac', models.CharField(blank=True, max_length=12, null=True)),
                ('bac2', models.CharField(blank=True, max_length=30, null=True)),
                ('specialite', models.CharField(blank=True, max_length=12, null=True)),
                ('annee_bac', models.IntegerField(blank=True, null=True)),
                ('annee_bac2', models.IntegerField(blank=True, null=True)),
                ('nomlycee', models.CharField(blank=True, max_length=100, null=True)),
                ('villelycee', models.CharField(blank=True, max_length=100, null=True)),
                ('codepostallycee', models.IntegerField(blank=True, null=True)),
                ('codelycee', models.CharField(blank=True, max_length=20, null=True)),
                ('etablissement_bac2', models.CharField(blank=True, max_length=20, null=True)),
                ('type_admission', models.CharField(blank=True, max_length=20, null=True)),
                ('boursier_prec', models.CharField(blank=True, max_length=20, null=True)),
                ('debouche', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Etudiants',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='code_nip',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
