# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0021_auto_20170902_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etudiant2',
        ),
    ]
