# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0011_remove_devoir_etudiant'),
        ('promotions', '0024_auto_20170902_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation_etudiant',
            name='etudiant',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='etudiants',
            field=models.ManyToManyField(through='promotions.Affectation_Etudiant', to='promotions.Etudiant2'),
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
