# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0027_auto_20170902_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='bac',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.CharField(blank=True, default='2017-09-01', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='specialite',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
