# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0028_auto_20170902_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='profile_image',
            new_name='photo',
        ),
    ]
