# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0029_auto_20170903_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/etudiants/'),
        ),
    ]
