# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0034_auto_20170923_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ics', models.URLField(verbose_name='Calendrier au format ics pour synchronisation')),
                ('commentaire', models.TextField(blank=True, max_length=400, null=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Groupe')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier_Hebdomadaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semaine', models.IntegerField(default=1)),
                ('annee', models.IntegerField(default=2017)),
                ('commentaire', models.TextField(blank=True, max_length=400, null=True)),
                ('calendrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Calendrier')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Affectation_Etudiant')),
            ],
            options={
                'ordering': ['annee', 'num_semaine'],
            },
        ),
    ]
