# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0035_calendrier_calendrier_hebdomadaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier_hebdomadaire',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.Affectation_Etudiant'),
        ),
    ]
