# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0038_auto_20170928_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='code_nip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
