# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0039_auto_20171001_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation_enseignant',
            options={'ordering': ['-groupe__promotion__annee', 'module'], 'verbose_name_plural': '4. Affectation Enseignant'},
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='ics',
            field=models.URLField(blank=True, null=True, verbose_name='Calendrier au format ics pour synchronisation'),
        ),
    ]
