# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import promotions.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0041_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justification',
            field=models.FileField(blank=True, null=True, upload_to=promotions.models.get_justification_path),
        ),
    ]
