# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0042_auto_20171012_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='enseignants',
            field=models.ManyToManyField(blank=True, to='formations.Enseignant'),
        ),
    ]
