# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import entreprises.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('num', models.IntegerField()),
                ('opca', models.CharField(blank=True, max_length=200, null=True)),
                ('remarques', models.TextField(blank=True, max_length=400, null=True, verbose_name='Remarques')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('siret', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=entreprises.models.get_image_path)),
                ('nomen_long', models.CharField(blank=True, max_length=100, null=True)),
                ('depet', models.IntegerField(blank=True, null=True)),
                ('l1_normalisee', models.CharField(blank=True, max_length=100, null=True)),
                ('l4_normalisee', models.CharField(blank=True, max_length=100, null=True)),
                ('l6_normalisee', models.CharField(blank=True, max_length=100, null=True)),
                ('l7_normalisee', models.CharField(blank=True, max_length=100, null=True)),
                ('apet700', models.CharField(blank=True, max_length=100, null=True)),
                ('libapen', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
                ('contrats', models.ManyToManyField(blank=True, related_name='contrat', to='entreprises.Contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Administratif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephonemobile', models.CharField(blank=True, max_length=20, null=True)),
                ('remarques', models.TextField(blank=True, max_length=400, null=True, verbose_name='Remarques')),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur_Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephonemobile', models.CharField(blank=True, max_length=20, null=True)),
                ('remarques', models.TextField(blank=True, max_length=400, null=True, verbose_name='Remarques')),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprises.Entreprise'),
        ),
    ]
