# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0004_auto_20170725_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqpm',
            name='intitule',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cqpm',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
