# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0005_auto_20170725_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqpm',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cqpm',
            name='intitule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
