# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0006_auto_20170725_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='num',
        ),
        migrations.AddField(
            model_name='contrat',
            name='intitule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
