# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0012_auto_20170726_1317'),
        ('entreprises', '0007_auto_20170725_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'ordering': ['-promotion__annee'], 'verbose_name_plural': '2. Contrats'},
        ),
        migrations.AlterModelOptions(
            name='entreprise',
            options={'ordering': ['nom'], 'verbose_name_plural': '1. Entreprise'},
        ),
        migrations.AddField(
            model_name='contrat',
            name='affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.Affectation_Etudiant'),
        ),
    ]
