# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0008_auto_20170726_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='promotion',
        ),
    ]
