# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0009_auto_20170726_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche_Liaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('mail_tuteur', models.EmailField(max_length=254)),
                ('fonction_tuteur', models.CharField(max_length=100)),
                ('telephone_tuteur', models.CharField(blank=True, max_length=30, null=True)),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé du stage (en quelques mots)')),
                ('adresse_stage', models.CharField(blank=True, max_length=200, null=True, verbose_name="Adresse de l'entreprise")),
                ('service', models.CharField(max_length=300, verbose_name='Service où le contrat est effectué')),
                ('programme', models.TextField(verbose_name='Objectifs de votre travail présentés lors de votre arrivée')),
                ('impression', models.TextField(verbose_name="Premières impressions sur l'accueil")),
                ('dates_visite', models.TextField(default='Pas de préférences', help_text="Jours et périodes les plus propices à une visite de l'enseignant ou indisponibilités de tuteur entreprise (si nécessaire) ", verbose_name='Dates préférentielles pour la visite')),
                ('problemes', models.TextField(default='Rien à signaler', verbose_name='Problèmes qui se posent éventuellement')),
            ],
            options={
                'verbose_name_plural': '3. Information',
            },
        ),
        migrations.CreateModel(
            name='Rapport_Tuteur_Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprentissage', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Aptitude à faire l'acquisition de connaissances ou d'aptitudes nouvelles", verbose_name="Facilité d'apprentissage")),
                ('ecoute', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Réceptivité aux directives et aux conseils fournis par l'encadrement", verbose_name='Ecoute et compréhension')),
                ('curiosite', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Intérêt pour le cadre de travail et ce qui s'y fait, indépendamment du travail demandé.", verbose_name='Curiosité')),
                ('imagination', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text='Aptitude à trouver des solutions originales aux problèmes qui se posent.', verbose_name='Imagination pratique')),
                ('jugement', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text='Les avis et choix du stagiaire paraissent-ils sûrs et bien étayés.', verbose_name='Jugement')),
                ('motivation', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Degré d'intérêt pour le travail demandé.", verbose_name='Motivation')),
                ('methode', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text='Sait mettre en oeuvre les moyens nécessaires à la réalisation de ses objectifs', verbose_name='Méthode - organisation')),
                ('autonomie', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="De 'ne demande conseil qu'à bon escient' à doit 'être tenu par la main'", verbose_name='Autonomie')),
                ('qualite', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="De 'a dépassé de loin en quantité et qualité ce qui était attendu' à 'a fourni un résultat très décevant'", verbose_name='Qualité du travail fourni')),
                ('dynamisme', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="De 'stimulé par les difficultés' à 'abandonne à la première difficulté'", verbose_name='Dynamisme et tenacité')),
                ('expression', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Qualité de la communication et de l'expression orale", verbose_name='Expression et langage')),
                ('relation', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Le stagiaire est de 'extrêmement apprécié' à 'difficilement admis' par les autres.", verbose_name="Relation avec l'entourage")),
            ],
            options={
                'verbose_name_plural': '5. Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Rapport_Tuteur_Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(default=datetime.datetime(2017, 7, 26, 17, 5, 43, 971716), help_text='format: année-mois-jours (exemple 2014-03-1)')),
                ('condition_travail', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')])),
                ('integration', models.IntegerField(choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], verbose_name="Intégration du stagiaire dans l'entreprise")),
                ('activite', models.TextField(verbose_name='Description des activités du stagiaire pendant la période passée')),
                ('visite', models.TextField(verbose_name='Déroulement de la visite, Objets des échanges')),
                ('commentaires', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Rapports de Visites',
            },
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={'ordering': ['-affectation__promotion__annee'], 'verbose_name_plural': '2. Contrats'},
        ),
        migrations.AddField(
            model_name='rapport_tuteur_formation',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.Contrat'),
        ),
        migrations.AddField(
            model_name='rapport_tuteur_entreprise',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.Contrat'),
        ),
        migrations.AddField(
            model_name='fiche_liaison',
            name='contrat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entreprises.Contrat'),
        ),
    ]
