# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0011_auto_20170726_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport_tuteur_formation',
            name='date_visite',
            field=models.DateField(default=datetime.date.today, help_text='format: année-mois-jours (exemple 2014-03-1)'),
        ),
    ]
