# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0012_auto_20170726_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'ordering': ['entreprise'], 'verbose_name_plural': '2. Contrats'},
        ),
        migrations.AddField(
            model_name='entreprise',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type',
            field=models.CharField(choices=[('CP', 'Contrat Professionnel'), ('CA', 'Contrat Apprentissage'), ('S', 'Stage'), ('Autre', 'Autre')], max_length=100, null=True),
        ),
    ]
