# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0013_auto_20170826_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
