# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0018_auto_20170902_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport_tuteur_formation',
            options={'ordering': ['-date_visite'], 'verbose_name_plural': '4. Rapports de Visites'},
        ),
    ]
