# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0019_auto_20170918_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'ordering': ['entreprise', '-affectation__promotion__annee'], 'verbose_name_plural': '2. Contrats'},
        ),
    ]
