# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0020_auto_20170919_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='gps_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='gps_long',
            field=models.FloatField(default=0),
        ),
    ]
