# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprises', '0021_auto_20170923_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteur_entreprise',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
