# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0022_tuteur_entreprise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuteur_entreprise',
            name='poste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
