# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0023_auto_20170927_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuteur_entreprise',
            options={'ordering': ['nom']},
        ),
        migrations.AlterField(
            model_name='tuteur_entreprise',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
