# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0024_auto_20170928_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport_tuteur_entreprise',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rapport_tuteur_entreprise',
            name='deadline',
            field=models.DateField(default=datetime.date.today, help_text='format: année-mois-jours (exemple 2014-03-1)', verbose_name='Evaluation à completer avant'),
        ),
        migrations.AddField(
            model_name='rapport_tuteur_entreprise',
            name='nom',
            field=models.CharField(default='Evaluation', max_length=100, verbose_name="Nom de l'évaluation"),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='apprentissage',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Aptitude à faire l'acquisition de connaissances ou d'aptitudes nouvelles", null=True, verbose_name="Facilité d'apprentissage"),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='autonomie',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="De 'ne demande conseil qu'à bon escient' à doit 'être tenu par la main'", null=True, verbose_name='Autonomie'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='curiosite',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Intérêt pour le cadre de travail et ce qui s'y fait, indépendamment du travail demandé.", null=True, verbose_name='Curiosité'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='dynamisme',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="De 'stimulé par les difficultés' à 'abandonne à la première difficulté'", null=True, verbose_name='Dynamisme et tenacité'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='ecoute',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Réceptivité aux directives et aux conseils fournis par l'encadrement", null=True, verbose_name='Ecoute et compréhension'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='expression',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Qualité de la communication et de l'expression orale", null=True, verbose_name='Expression et langage'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='imagination',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text='Aptitude à trouver des solutions originales aux problèmes qui se posent.', null=True, verbose_name='Imagination pratique'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='jugement',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text='Les avis et choix du stagiaire paraissent-ils sûrs et bien étayés.', null=True, verbose_name='Jugement'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='methode',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text='Sait mettre en oeuvre les moyens nécessaires à la réalisation de ses objectifs', null=True, verbose_name='Méthode - organisation'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='motivation',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Degré d'intérêt pour le travail demandé.", null=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='qualite',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="De 'a dépassé de loin en quantité et qualité ce qui était attendu' à 'a fourni un résultat très décevant'", null=True, verbose_name='Qualité du travail fourni'),
        ),
        migrations.AlterField(
            model_name='rapport_tuteur_entreprise',
            name='relation',
            field=models.IntegerField(blank=True, choices=[(4, 'Excellent'), (3, 'Très Bon'), (2, 'Bon'), (1, 'Passable'), (0, 'Non Satisfaisant')], help_text="Le stagiaire est de 'extrêmement apprécié' à 'difficilement admis' par les autres.", null=True, verbose_name="Relation avec l'entourage"),
        ),
    ]
