# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0026_auto_20171011_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport_tuteur_entreprise',
            name='modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
