# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0027_rapport_tuteur_entreprise_modification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport_tuteur_entreprise',
            options={'ordering': ['-deadline'], 'verbose_name_plural': '5. Evaluations'},
        ),
    ]
