# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0028_auto_20171012_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuteur_entreprise',
            options={'ordering': ['nom'], 'verbose_name_plural': '2. Tuteur Entreprise'},
        ),
    ]
