# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0008_auto_20170826_1222'),
        ('promotions', '0018_auto_20170824_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet_Tuteure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.DateTimeField(auto_now_add=True)),
                ('intitule', models.CharField(max_length=100, verbose_name='Intitulé du Projet')),
                ('salle', models.CharField(blank=True, max_length=100, null=True)),
                ('contexte', models.TextField(verbose_name='Contexte du Projet')),
                ('problematique', models.TextField(verbose_name='Problématique')),
                ('methodologie', models.TextField(verbose_name='Méthodologie')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('actif', models.BooleanField(default=False, verbose_name='Projet en cours')),
            ],
            options={
                'verbose_name_plural': '4. Projet Tuteurés',
            },
        ),
        migrations.CreateModel(
            name='Suivi_Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('nombre_heures', models.IntegerField()),
                ('travail_effectue', models.TextField(verbose_name='Travail effectué')),
                ('difficultes', models.TextField(verbose_name='Difficultés rencontrées')),
                ('suite', models.TextField(verbose_name='Suite envisagée')),
                ('remarqies', models.TextField(verbose_name='Remarque de l’enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Jury_Projet',
            fields=[
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projets.Projet_Tuteure')),
                ('horaire', models.DateTimeField(blank=True, null=True)),
                ('salle', models.CharField(blank=True, max_length=10, null=True)),
                ('accesseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='suivi_projet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Projet_Tuteure'),
        ),
        migrations.AddField(
            model_name='projet_tuteure',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant'),
        ),
        migrations.AddField(
            model_name='projet_tuteure',
            name='etudiant',
            field=models.ManyToManyField(blank=True, null=True, to='promotions.Etudiant'),
        ),
    ]
