# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0018_auto_20170824_0701'),
        ('projets', '0002_auto_20170827_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet_tuteure',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promotions.Promotion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet_tuteure',
            name='contexte',
            field=models.TextField(blank=True, null=True, verbose_name='Contexte du Projet'),
        ),
        migrations.AlterField(
            model_name='projet_tuteure',
            name='methodologie',
            field=models.TextField(blank=True, null=True, verbose_name='Méthodologie'),
        ),
        migrations.AlterField(
            model_name='projet_tuteure',
            name='problematique',
            field=models.TextField(blank=True, null=True, verbose_name='Problématique'),
        ),
    ]
