# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_auto_20170827_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet_tuteure',
            options={'ordering': ['-actif'], 'verbose_name_plural': '4. Projet Tuteurés'},
        ),
    ]
