# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_auto_20170918_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suivi_projet',
            old_name='remarqies',
            new_name='remarques',
        ),
    ]
