# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_auto_20170923_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet_tuteure',
            name='affectation',
            field=models.ManyToManyField(to='promotions.Affectation_Etudiant'),
        ),
    ]
