# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_auto_20170930_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet_tuteure',
            name='affectation',
            field=models.ManyToManyField(blank=True, to='promotions.Affectation_Etudiant'),
        ),
    ]
