# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import formations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation_Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponsabilite', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('nom_short', models.CharField(max_length=50)),
                ('profile_chef', models.ImageField(blank=True, null=True, upload_to='photos/chef_de_departement/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Départements',
            },
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice1', models.FileField(blank=True, null=True, upload_to=formations.models.get_devoir_path)),
                ('exercice2', models.FileField(blank=True, null=True, upload_to=formations.models.get_devoir_path)),
                ('exercice3', models.FileField(blank=True, null=True, upload_to=formations.models.get_devoir_path)),
                ('exercice4', models.FileField(blank=True, null=True, upload_to=formations.models.get_devoir_path)),
                ('exercice5', models.FileField(blank=True, null=True, upload_to=formations.models.get_devoir_path)),
                ('commentaire', models.TextField(blank=True, max_length=400, null=True)),
                ('modification', models.DateTimeField(auto_now=True)),
                ('changed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('nom', models.CharField(max_length=400)),
                ('file', models.FileField(upload_to=formations.models.get_document_path)),
                ('modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/enseignants/')),
                ('date_naissance', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('P', 'Permanent'), ('V', 'Vacataire')], default='P', max_length=1)),
                ('employeur', models.CharField(default='UBO', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephonemobile', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_rue', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_zip', models.IntegerField(blank=True, null=True)),
                ('adresse_ville', models.CharField(blank=True, max_length=100, null=True)),
                ('contraintes', models.TextField(blank=True, null=True, verbose_name='Contraintes')),
                ('confirmation', models.BooleanField(verbose_name='Confirmation Participation')),
            ],
            options={
                'ordering': ['nom'],
                'verbose_name_plural': '7. Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('nom_short', models.CharField(max_length=50)),
                ('profile_directeur', models.ImageField(blank=True, null=True, upload_to='photos/directeur/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Etablissements',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=400)),
                ('modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('deadline', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('BTS', 'BTS'), ('DUT', 'DUT'), ('L', 'Licence'), ('LP', 'Licence Pro'), ('M', 'Master'), ('MP', 'Master Pro')], default='LP', max_length=5)),
                ('domaine', models.CharField(max_length=100)),
                ('mention', models.CharField(max_length=200)),
                ('mention_short', models.CharField(blank=True, max_length=100, null=True)),
                ('date_accreditation', models.DateField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, max_length=2000, null=True)),
                ('competences', models.TextField(blank=True, max_length=2000, null=True)),
                ('active', models.BooleanField()),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Departement')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant')),
            ],
            options={
                'verbose_name_plural': '3. Formations',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_apogee', models.CharField(blank=True, max_length=20, null=True)),
                ('code_scodoc', models.CharField(blank=True, max_length=10, null=True)),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('intitule', models.CharField(max_length=100, verbose_name='Intitulé du module')),
                ('nb_heures_cours', models.FloatField()),
                ('nb_heures_td', models.FloatField()),
                ('nb_heures_tp', models.FloatField()),
                ('nb_ects', models.FloatField()),
                ('coefficient', models.FloatField()),
                ('objectifs', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Objectifs du module')),
                ('competences_minimales', models.TextField(blank=True, max_length=400, null=True, verbose_name='Compétences Minimales')),
                ('pre_requis', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Pré requis')),
                ('contenu', models.TextField(blank=True, max_length=2000, null=True)),
                ('modalites', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Modalité de Mise en Oeuvre')),
                ('mots_cles', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mots cles')),
                ('cc', models.BooleanField(default=False, verbose_name='Contrôle continu')),
                ('modification', models.DateTimeField(auto_now=True)),
                ('prolongements', models.ManyToManyField(blank=True, to='formations.Module')),
            ],
            options={
                'verbose_name_plural': '6. Modules',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nom_short', models.CharField(blank=True, max_length=100, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Formation')),
                ('modules', models.ManyToManyField(to='formations.Module')),
            ],
            options={
                'verbose_name_plural': '4. Parcours',
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('intitule', models.CharField(max_length=100)),
                ('nb_heures', models.FloatField()),
                ('nb_ects', models.FloatField()),
                ('coefficient', models.FloatField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Formation')),
            ],
            options={
                'verbose_name_plural': '5. UEs',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.UE'),
        ),
    ]
