# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='audience',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Module'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='directeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='groupes',
            field=models.ManyToManyField(through='promotions.Affectation_Enseignant', to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='modules',
            field=models.ManyToManyField(through='promotions.Affectation_Enseignant', to='formations.Module'),
        ),
        migrations.AddField(
            model_name='document',
            name='audience',
            field=models.ManyToManyField(blank=True, to='promotions.Groupe'),
        ),
        migrations.AddField(
            model_name='document',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant'),
        ),
        migrations.AddField(
            model_name='document',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Module'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Etudiant'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Evaluation'),
        ),
        migrations.AddField(
            model_name='departement',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant'),
        ),
        migrations.AddField(
            model_name='departement',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Etablissement'),
        ),
        migrations.AddField(
            model_name='departement',
            name='responsables',
            field=models.ManyToManyField(related_name='responsables', through='formations.Affectation_Responsable', to='formations.Enseignant'),
        ),
        migrations.AddField(
            model_name='affectation_responsable',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Departement'),
        ),
        migrations.AddField(
            model_name='affectation_responsable',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Enseignant'),
        ),
    ]
