# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_auto_20170724_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='formation',
            field=models.ManyToManyField(related_name='enseignant_formation', to='formations.Formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation_responsable', to='formations.Enseignant'),
        ),
    ]
