# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_auto_20170725_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-date_accreditation'], 'verbose_name_plural': '3. Formations'},
        ),
    ]
