# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_auto_20170725_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation_responsable',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='affectation_responsable',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='responsables',
        ),
        migrations.AddField(
            model_name='departement',
            name='enseignants',
            field=models.ManyToManyField(related_name='enseignants', to='formations.Enseignant'),
        ),
        migrations.DeleteModel(
            name='Affectation_Responsable',
        ),
    ]
