# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_auto_20170819_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['code_scodoc'], 'verbose_name_plural': '6. Modules'},
        ),
        migrations.AlterModelOptions(
            name='ue',
            options={'ordering': ['numero'], 'verbose_name_plural': '5. UEs'},
        ),
    ]
