# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_remove_enseignant_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='enseignants',
            field=models.ManyToManyField(related_name='departement_enseignant', to='formations.Enseignant'),
        ),
    ]
