# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_auto_20170826_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='modules',
        ),
        migrations.AddField(
            model_name='ue',
            name='parcours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.Parcours'),
        ),
    ]
