# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0009_auto_20170831_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ue',
            name='parcours',
        ),
        migrations.AddField(
            model_name='parcours',
            name='ues',
            field=models.ManyToManyField(to='formations.UE'),
        ),
    ]
