# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0010_auto_20170831_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='etudiant',
        ),
    ]
