# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import formations.models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0012_document4groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document4groupe',
            name='file',
            field=models.FileField(upload_to=formations.models.get_document4groupe_path),
        ),
    ]
