# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0014_enseignant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
