# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0023_auto_20170927_1510'),
        ('formations', '0015_auto_20170924_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='enseignants',
            field=models.ManyToManyField(to='formations.Enseignant'),
        ),
        migrations.AddField(
            model_name='formation',
            name='entreprises',
            field=models.ManyToManyField(to='entreprises.Entreprise'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tuteur_entreprises',
            field=models.ManyToManyField(to='entreprises.Tuteur_Entreprise'),
        ),
    ]
