# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0016_auto_20170927_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='enseignants',
            field=models.ManyToManyField(blank=True, to='formations.Enseignant'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='entreprises',
            field=models.ManyToManyField(blank=True, to='entreprises.Entreprise'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='tuteur_entreprises',
            field=models.ManyToManyField(blank=True, to='entreprises.Tuteur_Entreprise'),
        ),
    ]
