# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formations', '0017_auto_20170927_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/enseignants/')),
                ('date_naissance', models.DateField(auto_now_add=True)),
                ('employeur', models.CharField(default='UBO', max_length=100)),
                ('role', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephonemobile', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('commentaires', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='Confirmation Participation'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='administratifs',
            field=models.ManyToManyField(to='formations.Administratif'),
        ),
    ]
