# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0018_auto_20170928_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratif',
            options={'verbose_name_plural': '5. Administratif'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['nom'], 'verbose_name_plural': '4. Enseignants'},
        ),
    ]
