# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import formations.models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0019_auto_20170930_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='consigne_contrat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='consigne_projet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='grille_contrat',
            field=models.FileField(blank=True, null=True, upload_to=formations.models.get_grille_path),
        ),
        migrations.AddField(
            model_name='formation',
            name='grille_projet',
            field=models.FileField(blank=True, null=True, upload_to=formations.models.get_grille_path),
        ),
    ]
