# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0021_formation_consigne_feuille_emargement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document4groupe',
            options={'ordering': ['affectation_enseignant__module', 'nom']},
        ),
    ]
